name: 'Action-tag'
description: 'Greet someone and record the time'
inputs:
  token:  # id of input
    description: 'Token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'index.js'
